### ISSUE TITLE
Is it able to upload to SMB Server?

### ISSUE THREAD

**Issue by HTKT** [TimOliver/TOSMBClient#1]
May I know the SMB can send the data (ex: photo/video)to SMB server? Can use streaming directly? THanks

**Comment by TimOliver** [comment]
Hi! Sadly not. That's beyond the scope of the libDSM library. :(

The library is a very barebones implementation of the standard. The motivation behind the VideoLabs folks developing it was to simply be able to download video files, one-way to an iOS device for the VLC app. For that scenario, it would be a serious amount of effort to add file uploading for not a lot of significant gains.

As for streaming... the library downloads the files in chunks, so theoretically, streaming should be possible. But it's not possible for the scenario I'm planning to use this library (Downloading 50MB comic files), so I haven't looked into it.

Sadly, if you want to have file uploading, you might have to look into one of the commercial SMB licenses instead. Sorry!

**Comment by erolando** [comment]
:(

**Comment by sylverb** [comment]
I've implemented file upload (and lot of other write operations) in libdsm, it's now available in the libdsm repository ;)

**Comment by TimOliver** [comment]
@sylverb 

Hi Sylver! Yeah! I've been watching your pull requests over on the libdsm repo! Before you started contributing, I honestly thought that libdsm would never ever actually get SMB write support! I was so surprised. Thank you so much for that! :)

I'm swamped in some other things for the time being, but I'll see about exposing the write functionality in `TOSMBClient` as soon as I can.

If there's anything else you think needs doing on libdsm's side, please let me know! I'd be more than happy to help contribute over there some more!
