### ISSUE TITLE
Crash on doubled smb_session_destroy

### ISSUE THREAD

**Issue by natalia-osa** [TimOliver/TOSMBClient#11]
There is a crash (EXC_BAD_ACCESS) when the session is released during download. Stack presented below. The dealloc of my class just releases session: `_session = nil`. As you can see, firstly the `TOSMBSession -dealloc` is calling `smb_session_destroy` and just a moment later the same is called by `TOSMBDownloadTask -dealloc`. Because the object was already freed, the crash occurs.

![screen shot 2016-05-06 at 11 48 41](https://cloud.githubusercontent.com/assets/1477880/15069827/9bf02cbc-1380-11e6-90f0-8bcdc77b1ba6.png)

**Comment by TimOliver** [comment]
Fixed by your own PR. Thanks! :)
