### ISSUE TITLE
Memory pressure while downloading a large file

### ISSUE THREAD

**Issue by ValentinKuznetsov** [TimOliver/TOSMBClient#12]
I've discovered that when you try to download a file, the downloaded chunks are not being flushed to the disk and released from the memory as well. This causes the crash eventually (if file is big enough)

Most likely you might want to amend the following method:

`- (void)performDownloadWithOperation:(__weak NSBlockOperation *)weakOperation` in the `TOSMBSession` (line 470)

After the data is written to the disk, the `[fileHandle synchronizeFile];` should be called; I also think that the body of the `do {}` block should be wrapped inside the @autoreleasepool block, because you are creating an object of `NSData` there.

**Comment by natalia-osa** [comment]
My app just crashed - few memory warnings, and crash. Was trying to download 45s mp4 file (~60MB) on iPad 2. The same cause.

**Comment by TimOliver** [comment]
Woah! Nicely spotted! Thanks for that!

I just updated the code in the master branch to include an `@autoreleaspool` brace and the file synchronisation method call. Hopefully that'll help abate memory pressure when downloading files.

Thanks a lot! I'll get to the other issues when I get some more time! :)
