### ISSUE TITLE
smb_dir file missing on Xcode Project -[smb_dir  not included in TOSMBClient/libdsm/bdsm]

### ISSUE THREAD

**Issue by narendra-ct** [TimOliver/TOSMBClient#19]
Hi Tim,

I have tried to create a folder by using TOSMBClient and to create a folder it requires a method names as

**int smb_directory_create(smb_session *s, smb_tid tid, const char *path);**

method is available in smb_dir.h file, but the file is not included in TOSMBClient.Please include the file and update the framework if possible as early.

 /**
- @file smb_dir.h is missing
  */

Thanks,
Narendra V

**Comment by TimOliver** [comment]
Hi there!

Um, it should already be in there! I upgraded the framework to use the latest version of libdsm a few days ago:

https://github.com/TimOliver/TOSMBClient/blob/master/TOSMBClient/libdsm/bdsm/smb_dir.h

It's not exposed on the Objective-C level yet. That needs to be implemented in `TOSMBClient` and I don't have the time at the moment to that myself. That's being tracked here: https://github.com/TimOliver/TOSMBClient/issues/3

**Comment by narendra-ct** [comment]
yes, i can see in https://github.com/TimOliver/TOSMBClient/blob/master/TOSMBClient/libdsm/bdsm/smb_dir.h

and in finder also I'm able to find but when i include TOSMBClient in app its showing default i have to add it manually . After adding I'm not able to call the methods which are in smb_dir.h

**Comment by TimOliver** [comment]
Oh! Whoops! You're right! It's not actually in the project! I'm not sure how that happened!
Thanks for that! I just re-added it to the project and committed it.

**Comment by narendra-ct** [comment]
Hi thanks for the update and I'm able to create directories now. Im having one issue here

```
if (path.length == 0 || [path isEqualToString:@"/"]) {
    smb_share_list list;
    size_t shareCount = 0;
    **smb_share_get_list(self.session, &list, &shareCount);**
```

some times its crashing on the about line (smb_share_get_list(self.session, &list, &shareCount); with BAD_ACCESS, please let me know any thing to update.

Thanks,
Narendra

**Comment by TimOliver** [comment]
No problems!

Umm, sorry. I'm still learning how `libdsm` handles myself, so I can't offer any explanation for that. Off the top off my head, it MIGHT be a threading issue if two threads are trying to use the same copy of `self.session`, or it could be a proper issue in `libdsm`.)

If you find out what's causing it, please let me know! :)

**Comment by narendra-ct** [comment]
hi,

I got crash multiple times while downloading the large files from network with the following error, could you please helpme on this.

**_TOSMBClientExample(220,0x16e0a3000) malloc: **\* error for object 0x15711d600: incorrect checksum for freed object - object was probably modified after being freed._**

Thanks,
Narendra
