### ISSUE TITLE
how to read files directly

### ISSUE THREAD

**Issue by onean** [TimOliver/TOSMBClient#2]
how to play video through connect instead download

**Comment by TimOliver** [comment]
There's no API in `TOSMBClient` at the moment to allow partial read access to file on an SMB Share at the moment.

All of the file data is read via the `smb_fread` function of `libdsm`, so if you wanted to make a copy of the `TOSMBSessionDownloadTask` and refactor it into a task that provides chunks of data on demand, that would be relatively trivial to do. :)

If you're up to it, feel free to fork this project and implement it yourself. I'll gladly accept all pull requests. :)

In any case, it's beyond my requirements for this project (I just need file downloading), and I don't have the time to implement it, so I'm closing this issue.
