### ISSUE TITLE
Support for tvOS?

### ISSUE THREAD

**Issue by DeepakColworx** [TimOliver/TOSMBClient#20]
Everything integrates fine except for that part that libdsm.a is not supported on tvOS.

**Comment by TimOliver** [comment]
Hmm. I tried modifying my build script to compile against the tvOS SDK: https://gist.github.com/TimOliver/6fc822bf6863d1ebbf786f16d771f159

Unfortunately, it doesn't appear to be working out of the box. I'm not very familiar with how much the tvOS build process differs from iOS, so I'd need to have a longer play with it.

If you want, feel free to have a play with that build script and see if you can get it working! :)

**Comment by TimOliver** [comment]
Whoops! I spoke too soon! There was a typo in my build script! ^_^;;

Give this a try! The headers shouldn't need any changing; so just try dropping these two static libraries over the top of the iOS ones in your project and let me know if that works!

[libtasn_libdsm.zip](https://github.com/TimOliver/TOSMBClient/files/277351/libtasn_libdsm.zip)

**Comment by TimOliver** [comment]
Ping. :D

**Comment by DeepakColworx** [comment]
Wow, works like a charm. Thanks mate (y)

**Comment by DeepakColworx** [comment]
Thanks, works like a charm
