### ISSUE TITLE
Include of smb_session.h in smb_dir.h ...

### ISSUE THREAD

**Issue by naxos** [TimOliver/TOSMBClient#21]
...should be
# include "smb_session.h"

instead of
# include "bdsm/smb_session.h"

**Comment by TimOliver** [comment]
I'm not even sure why that was still building successfully on mine, but done!

**Comment by naxos** [comment]
Thanks. You probably didn't import smb_dir.h in your code.

**Comment by TimOliver** [comment]
That's probably it. No worries!
