### ISSUE TITLE
UNABLE TO unCompress zip file which is saved in document directory.

### ISSUE THREAD

**Issue by narendra-ct** [TimOliver/TOSMBClient#24]
Hi,

Im able to download the zip file from my shared folder and if try to unzip manually (in MAC) it works fine, if try to unzip the file using iOS Library (SSZipArchive or ZipArchive) it throws an error as BADZIP file.
The problem with only downloaded files and normal files i can able to unzip through SSZipArchive.
Please help on this what i can do.

Thanks,
Narendra V.

**Comment by narendra-ct** [comment]
While Download/Upload its creating more size than actual file size.

**Comment by narendra-ct** [comment]
hello,

I have fixed this issue by using While loop instead of do-while for **smb_fread** .

Code as follows: 

while ((bytesRead < self.file.fileSize))
    {
        @autoreleasepool {

```
        length = smb_fread(self.downloadSession, fileID, buffer, bufferSize);
        if (length != -1)
        {
            bytesRead += length;
            [fileHandle writeData:[NSData dataWithBytes:buffer length:length]];

            //Ensure the data is properly written to disk before proceeding
            [fileHandle synchronizeFile];

            self.countOfBytesReceived += length;

            [self didUpdateWriteBytes:length totalBytesWritten:self.countOfBytesReceived totalBytesExpected:self.countOfBytesExpectedToReceive];
        }
    }
}
```

**Comment by natalia-osa** [comment]
This seems to be a duplicate of https://github.com/TimOliver/TOSMBClient/issues/17. Good solution anyway.

**Comment by narendra-ct** [comment]
Yes, Im closing this.
