### ISSUE TITLE
Can't delete a folder when it contains any file/foder

### ISSUE THREAD

**Issue by arunTeneno** [TimOliver/TOSMBClient#28]
Hi
I am trying to delete a directory using: 
`int smb_directory_rm(smb_session *s, smb_tid tid, const char *path);` 

Its deleting folders but can't delete when folder contains any file.

Can you please suggest If I am missing something?

**Comment by fatenumber2** [comment]
Hi arunTeneno!

I am working on file or folder deletion too.
But return is always -2. Can you teach me how do you delete a file or folder, please ?

I add under function into TOSMBSession.
- (BOOL)deleteFile:(id)file
{
    // Return failed if file is not kind of class TOSMBSessionFile
    if ( ![file isKindOfClass:[TOSMBSessionFile class]] ){
        NSLog(@"Error : File is not kind of class TOSMBSessionFile");
        return NO;
    }
    
    // Return failed if smb_session is null
    if ( !self.session ){
        NSLog(@"Error : SMB_SESSION IS NULL");
        return NO;
    }
    
    // Get TOSMBSessionFile
    TOSMBSessionFile *session_file = (TOSMBSessionFile*)file;
    
    // Work out just the share name from the path (The first directory in the string)
    NSString *shareName = [self shareNameFromPath:session_file.filePath];
    
    // Get smb_tid
    smb_tid treeID = -1;
    smb_tree_connect(self.session, [shareName UTF8String], &treeID);
    if (treeID < 0) {
        NSLog(@"Error : Can not get SMB_TREE_ID");
        return NO;
    }
    
    // Process
    int status = smb_file_rm(self.session, treeID, [session_file.filePath UTF8String]);
    smb_tree_disconnect(self.session, treeID);
    
    return YES;
}

Did I missing something ?

**Comment by TimOliver** [comment]
Hi! That's a `libdsm` level API, so you might be better off asking it at the [libdsm repo](https://github.com/videolabs/libdsm/). :)
