### ISSUE TITLE
Uploading / Modifying Files on the SMB Share

### ISSUE THREAD

**Issue by erolando** [TimOliver/TOSMBClient#3]
Hi

Soon, write file?

**Comment by TimOliver** [comment]
Haha, it looks like you already saw the closed issue from another user who already requested it.

You'll be happy to know that a very awesome user named @sylverb recently added write support to libdsm, making the ability to add write support to this library possible now!

I'm sadly a bit busy working on integrating the 'read' aspect of SMB into my app project right now, and while I'll definitely need the 'write' ability as well in the future, I haven't got the time to add it right now.

If you need it urgently, feel free to fork my library, duplicate the 'download task' class and turn it into an 'upload task'. I just finished updating the library to the latest version of libdsm, so the upload APIs are already available in there. :)

**Comment by fatenumber2** [comment]
Hi TimOliver

Thanks for awesome library.

I want to create function to upload file using smb_fwrite().
But I think first I must to create new file before upload, and I can not find any function to do that.

Can you help how to create new smb file, please T_T
Thanks again.

**Comment by haemi** [comment]
any updates on this?

**Comment by TimOliver** [comment]
Yep!
