### ISSUE TITLE
Can be use this lib in Microsoft Windows platform 

### ISSUE THREAD

**Issue by isurukej** [TimOliver/TOSMBClient#35]
Can be use this lib in standard file sharing protocol on the Microsoft Windows platform (Windows 7, 8, 10)?

**Comment by TimOliver** [comment]
This particular library cannot. Because it's written in Objective-C.

But the underlying library, [libdsm](https://github.com/videolabs/libdsm) is just C, so that should easily compile for Windows. :)

**Comment by isurukej** [comment]
Thanks your reply
