### ISSUE TITLE
How connect to computer with without ASCII name and login?

### ISSUE THREAD

**Issue by DimonDeveloper** [TimOliver/TOSMBClient#4]
I need to use UTF8 for name and login. (cyrillic, chinese etc.)
Please tell me how to change the encoding?

**Comment by TimOliver** [comment]
Erm, it should already be doing that. Whenever an `NSString` needs to be passed to libdsm, it's converted into its equivalent UTF8 C string (Example: https://github.com/TimOliver/TOSMBClient/blob/master/TOSMBClient/TOSMBSession.m#L234)

Is it not working for you?

**Comment by DimonDeveloper** [comment]
In a sample, after open SMB Devices view, hostname on cyrillic "Наташа" looks like "??'???". User name the same of host name "Наташа". 
`[session setLoginCredentialsWithUserName:@"Наташа" password:@"001133"];` 
i get alert "Login authentication failed"
![screen shot 2016-04-26 at 7 13 24 pm](https://cloud.githubusercontent.com/assets/3527457/14825533/04ea87f8-0be3-11e6-85a2-0f84cb1f5380.png)

I check this on another computer with latin host and username and everything is fine.

After that try this:
`TOSMBSession *session = [[TOSMBSession alloc] initWithHostName:@"Наташа" ipAddress:entry.ipAddressString];
[session setLoginCredentialsWithUserName:@"Наташа" password:@"001133"];`
And get alert "Insufficient information to resolve device address".
![screen shot 2016-04-26 at 7 11 34 pm](https://cloud.githubusercontent.com/assets/3527457/14825455/be9fc89e-0be2-11e6-8918-691ae0228290.png)

**Comment by TimOliver** [comment]
Hmm, I really don't know, sorry. All my string conversion code goes between UTF8, so if it's not working, it could potentially be a libdsm-level issue.

libdsm comes with several CLI utilities that you can build and then use to test out its connection functionality. Try building those and see if you get the same problem there: https://github.com/videolabs/libdsm

Good luck!
