### ISSUE TITLE
outdated version on cocoapods?

### ISSUE THREAD

**Issue by beks6** [TimOliver/TOSMBClient#48]
## Hardware / Software

Which version of the library were you using?
1.0.5
Which version of iOS are you running?
10.3.1 (iPhone) 10 (Simulator)
What model of iOS device were you testing on?
iPhone 7 and Simulator
If using CocoaPods, which version of CocoaPods are you on?
1.2.1

## Goals

What is the outcome result you want to achieve with this library?
create folders and upload photos

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)
missing uploadtask file and unable to update the library over cocoapods

**Comment by TimOliver** [comment]
Thanks @beks6. I updated the pod to v1.0.7. It should contain the latest APIs now. :)
