### ISSUE TITLE
Asynchronous (request-)call not working properly

### ISSUE THREAD

**Issue by rajderks** [TimOliver/TOSMBClient#55]
## Hardware / Software

Which version of the library were you using? **1.0.8 (cocoa pods latest)**
Which version of iOS are you running? **11.0**
What model of iOS device were you testing on? **iPhone SE, some iPad (not air or pro)**
If using CocoaPods, which version of CocoaPods are you on? **1.3.1**
**USING SWIFT 4, xCode 9.1**

## Goals

What is the outcome result you want to achieve with this library?
Request files from local SMB server (MacBook High Sierra, public folder sharing using SMB, with account + password)

## Expected Results

What did you expect to happen?
A listing of my public folder
```
SYNC CALL : Optional([Dir - Name: Drop Box | Size: 0, File - Name: 31F6603F-3251-4A51-8516-A67C8080A751.mp4 | Size: 1137622])
ASYNC CALL: Optional([Dir - Name: Drop Box | Size: 0, File - Name: 31F6603F-3251-4A51-8516-A67C8080A751.mp4 | Size: 1137622])
```

## Actual Results
```
SYNC CALL : Optional([Dir - Name: Drop Box | Size: 0, File - Name: 31F6603F-3251-4A51-8516-A67C8080A751.mp4 | Size: 1137622])
ASYNC CALL: nil
```

## Steps to Reproduce

What are the steps needed to reproduce this issue?
```
        let session = TOSMBSession.init(hostName: "xxx", ipAddress: "192.xxx.x.xxx")
        session?.setLoginCredentialsWithUserName("redacted", password: "super-redacted")

        let content = try! session?.requestContentsOfDirectory(atFilePath: "/<public folder>/")
        print("\(String(describing: content))") // Prints the files
        
        session?.requestContentsOfDirectory(atFilePath: "/<public folder>/", success: { (content) in
            print("\(String(describing: content))") // Always prints nil
        }, error: { (error) in
            if let error = error {
                print(error.localizedDescription)
            }
        })
```

After tracing its steps, the asynchronous call never calls the synchronous call
**TOSMBSession.m:353**        ` NSArray *files = [**weakSelf** requestContentsOfDirectoryAtFilePath:path error:&error];`

Chaning **weakSelf** to **self** fixes the issue, and works as expected. However, I do not know what consequences this might have.

**Comment by TimOliver** [comment]
Thanks for the issue @rajderks!

I think the issue here is you need to hang onto your `session` object more permanently. I think what's happening here is you're creating it, performing this asynchronous request, and then by the time it completes, this original method has already completed and `session` has already been deallocated.

If you make `session` a property of your parent class, that should fix it.

Hope that helps!

**Comment by rajderks** [comment]
@TimOliver your comment makes perfect sense; and it is also working as aspected when declaring it as a property. Thank you!

**Comment by TimOliver** [comment]
Awesome! Thanks a lot for that @rajderks! Glad I could help! ^_^
