### ISSUE TITLE
Compiling libdsm errors

### ISSUE THREAD

**Issue by ThomasAriano** [TimOliver/TOSMBClient#59]
Hey Tim, I know this issue doesn't fit the template, but I could really use some help. I've found several different gist scripts you posted to compile the library, but I can't get any of them to work. I am using MacOS and this script https://gist.github.com/TimOliver/0a67da72b097c42c7552043aca48bc86. Libtasn1 finishes without any problems, but I get this error for all libdsm arches:

make[1]: asn1Parser: No such file or directory
make[1]: *** [contrib/spnego/spnego_asn1.c] Error 1
make: *** [all] Error 2

I tried the script for MacOS that you suggested, but it didn't seem to work at all. If I can compile it on another operating system, please let me know how. I assume I need MacOS for the xcode iphone sdks. How did you originally compile it?

Not sure if it's relevant, but I am trying to compile a locally modified library in which I fixed netbios name lookups (seems that libdsm was a bit broken). Thank you!

**Comment by ThomasAriano** [comment]
Just needed to brew install libtasn1

**Comment by TimOliver** [comment]
Hi @ThomasAriano! 

Ahhh! That’s good to hear! I wasn’t going to be sure how to answer that. That’s good to know!

Thanks!
