### ISSUE TITLE
Crash with multiple downloads at the same time

### ISSUE THREAD

**Issue by sumanksk2006** [TimOliver/TOSMBClient#6]
Hi,

I am trying to download multiple files from SMB to iPad's app Sandbox.  

I am getting following error and app gets crashed
malloc: **\* error for object 0x7f9c88c56860: pointer being freed was not allocated.

So, I tried with TOSMBClientExamble too. But, I got the same issue as above.

From code wise, I get SIGABRT at smb_session_login in attemptConnectionWithSessionPointer before file download gets start.

If I avoid the above step, I get SIGABRT at smb_tree_connect. Sometimes, Its not creating treeID and app gets crashed resulting to SIGABRT at smb_fopen.

Can you please help me to solve this issue?

Thanks,
Suman

**Comment by natalia-osa** [comment]
Just for a quick-fix, you may edit `setupDownloadQueue` in `TOSMSession` and add `self.downloadsQueue.maxConcurrentOperationCount = 1;`. Anyway, this should be configurable (I did it also). I will try to make a fork & pull request with this when I have a free moment.

**Comment by TimOliver** [comment]
I had a play with this last night, and I discovered it too when I tried to download more than 2 files at once.

I discovered that `libdsm` seems to fail if multiple session handles are trying to authenticate at the same time (i.e., calling `smb_session_login` concurrently). I enclosed the method calls to the initial device connection in a serial dispatch queue run by the parent `TOSMBSession` object and it worked fine after that. I tested download 5 files at the same time, and they all came down without issue.

It probably needs some more refining though. The timeout length for the TCP connections is crazy long, and at the moment, if that actually happens, it'll repeat itself serially in each queue. :/

In any case, the error message is cleared up, so this issue can at least be resolved. :)

**Comment by shishaozheng** [comment]
Hi Tim,
Still have this bug when I use this library with cocoapods, The libdsm has fixed this bug (https://github.com/videolabs/libdsm/issues/74), so I think upgrade to latest dev libdsm(the latest released version is 0.3.0 which is not include this fix) will fix this bug, but the coacoapods lib is still using libdsm 0.2.8 right?
